week8/recipes/recipefind/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('recipefind.views',
    (r'^$', 'index'),
    (r'^(?P<recipe_id>\d+)/$', 'detail'),
    (r'^(?P<ingredient>\w+)/$', 'ingredient'),
)

week8/recipes/urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^recipes/', include('recipefind.urls')),
    (r'^admin/', include(admin.site.urls)),
)

week8/recipes/recipefind/models.py
from django.db import models

class Recipe(models.Model):
    name = models.CharField(max_length=200)
    pub_date = models.DateField('date added')
    main_ingredient = models.CharField(max_length=200)
    prep_time = models.IntegerField('Prep Time(minutes)')
    cook_time = models.IntegerField('Cook Time(minutes)')
    def time_required(self):
        return self.prep_time + self.cook_time
    time_required.short_description = 'Time Required (minutes)'
    def __unicode__(self):
        return self.name

class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe)
    ingredient = models.CharField(max_length=200)
    quantity = models.CharField(max_length=100)
    def __unicode__(self):
        return self.ingredient

class Instructions(models.Model):
    recipe = models.ForeignKey(Recipe)
    instructions = models.TextField(max_length=800)
    def __unicode__(self):
        return self.instructions

week8/recipes/recipefind/views.py
from django.shortcuts import render_to_response, get_object_or_404
from recipefind.models import Recipe

def index(request):
    recipe_list = Recipe.objects.all().order_by('name')[:5]
    return render_to_response('recipefind/index.html', {'recipe_list': recipe_list})

def detail(request, recipe_id):
    r = get_object_or_404(Recipe, pk=recipe_id)
    return render_to_response('recipefind/detail.html', {'recipe': r})

def ingredient(request, ingredient):
    recipe_list = Recipe.objects.filter(main_ingredient=ingredient)
    return render_to_response('recipefind/ingredient.html', {'recipe_list': recipe_list, 'main_ingredient':ingredient})

week8/recipes/templates/recipefind/detail.html
<h1>Recipe for {{ recipe.name }}</h1>
<B>Total Time Required:</B> {{ recipe.time_required }} minutes
<BR><B>Prep Time:</B> {{ recipe.prep_time }} minutes
<BR><B>Cook Time:</B> {{ recipe.cook_time }} minutes
<P><table border="1">
<tr>
<th>Ingredient</th>
<th>Quantity</th>
</tr>
{% for ingredient in recipe.ingredient_set.all %}
    <tr><td>{{ ingredient.ingredient }}</td>
    <td>{{ ingredient.quantity}}</td></tr>
{% endfor %}
</table>
<BR>
{% for instructions in recipe.instructions_set.all %}
    <B>Instructions:</B><BR>
    {{instructions.instructions}}
{% endfor %}
<p><a href="/recipes/">Back to Index</a>

week8/recipes/templates/recipefind/index.html
<h1>Recipe List: All Recipes</h1>
{% if recipe_list %}
    <table border="1">
    <tr>
    <th>Dish</th>
    <th>Main Ingredient</th>
	<th>Total Time Required</th>
    </tr>
    {% for recipe in recipe_list %}
        <tr><td><a href="/recipes/{{ recipe.id }}/">{{ recipe.name }}</a></td>
        <td><a href="/recipes/{{ recipe.main_ingredient }}/">{{ recipe.main_ingredient }}</a></td>
		<td>{{ recipe.time_required }} minutes</td></tr>
    {% endfor %}
{% else %}
    <p>No recipes are available.</p>
{% endif %}

week8/recipes/templates/recipefind/ingredient.html
<h1>Recipe List: Main ingredient {{ main_ingredient }}</h1>
{% if recipe_list %}
    <table border="1">
    <tr>
    <th>Dish</th>
    <th>Main Ingredient</th>
	<th>Total Time Required</th>
    </tr>
    {% for recipe in recipe_list %}
        <tr><td><a href="/recipes/{{ recipe.id }}/">{{ recipe.name }}</a></td>
        <td>{{ recipe.main_ingredient }}</td>
		<td>{{ recipe.time_required }} minutes</td></tr>
    {% endfor %}
{% else %}
    <p>No recipes are available.</p>
{% endif %}
<p><a href="/recipes/">Back to Index</a>